spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    password: postgres
#    hikari:
#      schema: cloudtechies
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
com:
  iris:
    hackathon:
      respCSVHeader: 'Record Number, Transaction Id, Status'
      respRootPath: /anand/temp/mnt/response
      kafkaExponentialBackOffInitialInterval: '3000'
      kafkaExponentialBackOffMultiplier: '3'
      kafkaConsumerGroupName: payloadProcessor
      maxPollSize: 100
      kafkaClusterURL: localhost:9092
      kafkaPersistPayloadTopic: client-resp-queue
server:
  port: 8084
